/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnijava_JniTest */

#ifndef _Included_jnijava_JniTest
#define _Included_jnijava_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnijava_JniTest
 * Method:    getPackname
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnijava_JniTest_getPackname
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
